### ISSUE TITLE
Potential security threat 

### ISSUE THREAD

**Issue by barakadanny** [wechu07/leave-no-medic-behind#2]
# Security issue

The access token generation function for the Safaricom API in [src/middleware/generateAccessToken.js](https://github.com/wechu07/leave-no-medic-behind/blob/master/src/middleware/generateAccessToken.js) seems to be functional, but there are a few improvements that could be made to enhance its security.

# Expected Behavior

The function should validate the inputs for the Safaricom API credentials, 
```js
     process.env.SAFARICOM_CONSUMER_KEY
```
and 
```js
     process.env.SAFARICOM_CONSUMER_SECRET
```
both should be validated before they are used. This will help to prevent potential security vulnerabilities such as injecting malicious code.

# Current Behavior

The inputs for the Safaricom API credentials are not being validated

# Failure Information (for bugs)

### Steps to Reproduce

1. Call the `accessToken` function
2. Observe the behaviour of the inputs from the Safaricom API credentials

**Comment by wechu07** [comment]
Thank you chief. Will look into that @barakadanny
